version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
    image: flaskapp:${IMAGE_TAG}
    container_name: flaskapp
    #ports:
    # - "8000:8000"
    network_mode: host

  nginx:
    build: ./nginx
    image: nginx:${IMAGE_TAG}
    container_name: nginx
    environment:
      - SERVER_NAME=34.234.85.179
    restart: always
    network_mode: host
