apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-deployment
  labels:
    app: flask-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: flaskapp
          image:  340752824368.dkr.ecr.us-east-1.amazonaws.com/flaskapp:latest
          ports:
            - containerPort: 8000
        - name: nginx
          image: 340752824368.dkr.ecr.us-east-1.amazonaws.com/flask-nginx:latest
          ports:
            - containerPort: 80
      
      
