apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-deployment
  labels:
    app: flask-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
      annotations:                            # ✅ Must be sibling to labels
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"            # ✅ Matches flaskapp's containerPort
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: flaskapp
          image: 340752824368.dkr.ecr.us-east-1.amazonaws.com/flaskapp:latest
          ports:
            - containerPort: 8000
        - name: nginx
          image: 340752824368.dkr.ecr.us-east-1.amazonaws.com/flask-nginx:latest
          ports:
            - containerPort: 80
