apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  type: NodePort  # Use LoadBalancer if on AWS EKS
  selector:
    app: flask-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
